// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnipjjcqlpklyuaduwml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuaXBqamNxbHBrbHl1YWR1d21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjUxOTksImV4cCI6MjA2ODc0MTE5OX0.piOyNpxl7vZ1nf1NS4Klp2M-mDpyoCvlczcCH3WubD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'Accept-Profile': 'public'
    }
  }
});